FROM python:3.10-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    libglib2.0-0 \
    libgl1 \
    libgomp1 \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt
RUN python -c "import easyocr; easyocr.Reader(['ar','en'], gpu=False)"

COPY . .

EXPOSE 5050

CMD ["gunicorn", "-w", "1", "-b", "0.0.0.0:5050", "ocr_api:app", "--timeout", "180"]